In [3]:
#Program-1 
#XML File
import xml.etree.ElementTree as ET
tree= ET.parse('C:/Users/bharg/Desktop/Festivals_and_Events_v9_fromArchivedb.xml')
root = tree.getroot()
print(f'Total Events: {len(root)}\n')
count = 0
print('Entry data Attributes:')
for event in root.findall("./viewentry/entrydata"): 
    if count == 61: 
        break
    print(event.attrib)
    count += 1
print('\n\n')
count = 0
for event in root.findall(".viewentry"):
    if count == 5: break
    print(f'Event {count + 1}')
    print('Name: '+ event.find(".//*[@name='EventName']/text").text)
    print('Area: ' + event.find(".//*[@name='Area']/text").text)
    print('Categories: ' + ', '.join(cat.text for cat in event.findall(".//*[@name='CategoryList']//textlist//text")))
    print('Date Begin Show: ' + event.find(".//*[@name='DateBeginShow']/text").text)
    print('Admission: ' + event.find(".//*[@name='Admission']/text").text  + '\n')
    count += 1

Total Events: 1000

Entry data Attributes:
{'columnnumber': '0', 'name': 'EventName'}
{'columnnumber': '1', 'name': 'Area'}
{'columnnumber': '2', 'name': 'CategoryList'}
{'columnnumber': '3', 'name': 'PresentedByOrgName'}
{'columnnumber': '4', 'name': 'Image'}
{'columnnumber': '5', 'name': 'DateBeginShow'}
{'columnnumber': '6', 'name': 'TimeBegin'}
{'columnnumber': '7', 'name': 'DateEndShow'}
{'columnnumber': '8', 'name': 'TimeEnd'}
{'columnnumber': '9', 'name': 'Admission'}
{'columnnumber': '10', 'name': 'LongDesc'}
{'columnnumber': '11', 'name': 'OrgContactPhone'}
{'columnnumber': '12', 'name': 'OrgContactExt'}
{'columnnumber': '13', 'name': 'Location'}
{'columnnumber': '14', 'name': 'Intersection'}
{'columnnumber': '15', 'name': 'MapAddress'}
{'columnnumber': '16', 'name': 'TTC'}
{'columnnumber': '17', 'name': 'EventURL'}
{'columnnumber': '18', 'name': 'ImageAltText'}
{'columnnumber': '19', 'name': 'OrgContactEMail'}
{'columnnumber': '20', 'name': 'AccessibleFully'}
{'columnnumber': '21', 'name': 'ParkingFree'}
{'columnnumber': '22', 'name': 'PublicWashrooms'}
{'columnnumber': '23', 'name': 'AccessiblePartially'}
{'columnnumber': '24', 'name': 'ParkingPaid'}
{'columnnumber': '25', 'name': 'FoodBeverage'}
{'columnnumber': '26', 'name': 'Shopping'}
{'columnnumber': '27', 'name': 'Exhibit'}
{'columnnumber': '28', 'name': 'Performance'}
{'columnnumber': '29', 'name': 'KidFriendly'}
{'columnnumber': '30', 'name': 'History'}
{'columnnumber': '31', 'name': 'Green'}
{'columnnumber': '32', 'name': 'NewThisYear'}
{'columnnumber': '33', 'name': 'Reservations'}
{'columnnumber': '34', 'name': 'OfficialGreenSite'}
{'columnnumber': '35', 'name': 'BikeRacks'}
{'columnnumber': '36', 'name': 'RoadClose'}
{'columnnumber': '37', 'name': 'OrganicFood'}
{'columnnumber': '38', 'name': 'Address'}
{'columnnumber': '39', 'name': '$6'}
{'columnnumber': '40', 'name': 'txtGeoId'}
{'columnnumber': '41', 'name': 'txtLong'}
{'columnnumber': '42', 'name': 'txtLat'}
{'columnnumber': '43', 'name': 'NumberLocations'}
{'columnnumber': '44', 'name': 'LocationType_1'}
{'columnnumber': '45', 'name': 'Location_1'}
{'columnnumber': '46', 'name': '$13'}
{'columnnumber': '47', 'name': '$14'}
{'columnnumber': '48', 'name': 'TTC_1'}
{'columnnumber': '49', 'name': 'Address_1'}
{'columnnumber': '50', 'name': 'txtGeoId_1'}
{'columnnumber': '51', 'name': 'txtLong_1'}
{'columnnumber': '52', 'name': 'txtLat_1'}
{'columnnumber': '53', 'name': 'LocationType_2'}
{'columnnumber': '54', 'name': '$21'}
{'columnnumber': '55', 'name': '$22'}
{'columnnumber': '56', 'name': 'TTC_2'}
{'columnnumber': '57', 'name': 'Address_2'}
{'columnnumber': '58', 'name': 'txtGeoId_2'}
{'columnnumber': '59', 'name': 'txtLong_2'}
{'columnnumber': '60', 'name': 'txtLat_2'}



Event 1
Name: '72 Summit Series Tour
Area: Downtown
Categories: History, Sports
Date Begin Show: Sep 10, 2016
Admission: $80 - $89

Event 2
Name: '72 Summit Series Tour
Area: Downtown
Categories: History, Sports
Date Begin Show: Sep 10, 2016
Admission: $80 - $89

Event 3
Name: ‘Antiques Roadshow’-inspired Open Call for Canadian Art
Area: Downtown
Categories: Arts/Exhibits, Seminars/Workshops
Date Begin Show: May 9, 2014
Admission: Free

Event 4
Name: ‘Antiques Roadshow’-inspired Open Call for Canadian Art
Area: Downtown
Categories: Arts/Exhibits, Seminars/Workshops
Date Begin Show: May 9, 2014
Admission: Free

Event 5
Name: ‘Antiques Roadshow’-inspired Open Call for Canadian Art
Area: Downtown
Categories: Arts/Exhibits, Seminars/Workshops
Date Begin Show: May 9, 2014
Admission: Free

In [3]:
#Part 1 - Web Services
#JSON file
import json
import re
def dict_keys(data,father, level):
    result = []
    for key in data.keys():
        if type(data[key]) != dict and type(data[key]) != list:
            result.append('\t'*level + key + '\n')
        else:
            if type(data[key]) == dict:
                result.append('\t'*level + key + ':\n' + '\t'*(level) + '{\n')
                level += 1
                result += dict_keys(data[key], key, level)
                level -= 1
            else: 
                if len(data[key]) == 0:
                    result.append('\t'*level + key + '\n')
                else:
                    result.append('\t'*level + key + ':\n' + '\t'*(level) + '{\n')
                    level += 1
                    for i in range(len(data[key])):
                        result += dict_keys(data[key][i], key, level)
                    level -= 1
    if level != 0:
        result.append('\t'*(level-1) + '}\n')
    return result
with open('C:/Users/bharg/Desktop/edc_eventcal_APR.json') as file_data:
    events = json.load(file_data)
print(f'Total Events: {len(events)}\n')

print('Data structure:')
print (''.join(key for key in dict_keys(events[0],'', 0)))
print('\n')
print('Last 5 events:')
for event in events[:len(events)-6:-1]:
    print(f"Name: {event['calEvent']['eventName']}")
    print(f"Location: {event['calEvent']['locations'][0]['locationName']}")
    print(f"Categories: {event['calEvent']['categoryString']}")
    print("Start date: ", re.findall('\d\d\d\d-\d\d-\d\d', event['calEvent']['startDate'])[0])
    print(f"Free: {event['calEvent']['freeEvent']}\n")

Total Events: 390

Data structure:
calEvent:
{
	orgType
	startDate
	thumbImage:
	{
		fileSize
		fileType
		binId
		fileName
		url
	}
	orgAddress
	terms
	endDate
	frequency
	partnerType
	eventWebsite
	orgPhone
	eventEmail
	locations:
	{
		id
		coords:
		{
			lng
			lat
		}
		$$hashKey
		address
		geoCoded
		locationType:
		{
			type
		}
		locationName
		type
	}
	dates:
	{
		startDateTime
	}
		startDateTime
	}
		startDateTime
	}
		startDateTime
	}
		startDateTime
	}
		startDateTime
	}
	description
	orgEmail
	features:
	{
		Public Washrooms
	}
	categoryString
	themeString
	isWidgetEvent
	accessibility
	admissionType
	partnerName
	subsetCalendarString
	theme:
	{
		name
	}
	image:
	{
		fileSize
		fileType
		binId
		fileName
		altText
		url
	}
	reservationsRequired
	recId
	orgName
	cost:
	{
		to
		from
	}
	eventPhone
	category:
	{
		name
	}
		name
	}
		name
	}
	shortDescription
	admin:
	{
		reviewerComments
		updateTimestamp
		newsletterCategory:
		{
			value
		}
		includeInNewsletter
		newsletterSubcategory
		featuredEvent
		approvedTimestamp
		subsetCalendar
		approvedBy
		updatedBy
	}
	contactName
	reservation:
	{
		phone
		website
		email
	}
	freeEvent
	eventName
}



Last 5 events:
Name: Len Cariou &#8211; Broadway &amp; the Bard An Evening of Shakespeare and Song
Location: Toronto Centre for the Arts - Greenwin Theatre
Categories: Live Performances,Theatre
Start date:  2019-06-06
Free: No

Name: Pyjama Cruise
Location: The Empress of Canada
Categories: Charity/Cause,Dance,Music
Start date:  2019-06-14
Free: No

Name: Mystery &amp; Magic Feat. Beyond Mental Borders
Location: The Rec Room
Categories: Family/Children,Live Performances
Start date:  2019-06-16
Free: No

Name: 1855 Toronto Circus Riot
Location: 181 Sterling Road
Categories: Arts/Exhibits,Live Performances
Start date:  2019-06-05
Free: No

Name: Nature Drawing and Journaling - 'The Life of a Dead Tree'
Location: MOCA Toronto
Categories: Arts/Exhibits,Museum,Seminars/Workshops
Start date:  2019-05-30
Free: No

In [6]:
#Part 2 - War Card Game
import random
class card:
    def __init__(self, suit, value):
        self.suit = suit
        self.value = value
class deckOfCards:
    deck = []
    def __init__(self):
        suits = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
        values = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']
        for s in suits:
            for v in values:
                self.deck.append(card(s, v))
    def shuffle(self):
        self.deck = random.sample(self.deck, len(self.deck))
    def deal(self):
        p1 = self.deck.pop(0)
        p2 = self.deck.pop(0)
        return p1, p2
def print_deck(doc):
    for card in doc.deck: print(f'{card.value} {card.suit}')
num_values = {'A': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7,\
            '8': 8, '9': 9, '10': 10, 'J': 11, 'Q': 12, 'K': 13}
while(True):
    input('Enter any key to start...')
    doc = deckOfCards()
    doc.shuffle()
    count_player = 0
    count_opp = 0
    while(len(doc.deck) > 0):
        p1, p2 = doc.deal()
        print(f'Your card: {p1.value} {p1.suit} \tOpponent\'s card: {p2.value} {p2.suit}')
        if num_values[p1.value] == num_values[p2.value]:
            print('WAR')
        elif num_values[p1.value] > num_values[p2.value]:
            print('You win the hand!')
            count_player += 1
        else:
            print('You lose the hand')
            count_opp += 1
    if(count_player > count_opp):
        print(f'\nYOU WIN: {count_player} x {count_opp}')
    elif(count_player < count_opp):
        print(f'\nYOU LOSE: {count_player} x {count_opp}')
    else:
        print(f'\nWAR: {count_player}')
    inValue = input('\nEnter any key to \'q\' to quit')
    if inValue == 'q': break

Enter any key to start...b
Your card: K Hearts 	Opponent's card: J Clubs
You win the hand!
Your card: K Spades 	Opponent's card: 4 Clubs
You win the hand!
Your card: 4 Diamonds 	Opponent's card: 8 Diamonds
You lose the hand
Your card: 5 Spades 	Opponent's card: 6 Hearts
You lose the hand
Your card: 9 Spades 	Opponent's card: 4 Hearts
You win the hand!
Your card: J Diamonds 	Opponent's card: 4 Spades
You win the hand!
Your card: 10 Clubs 	Opponent's card: J Hearts
You lose the hand
Your card: 2 Hearts 	Opponent's card: 9 Clubs
You lose the hand
Your card: K Diamonds 	Opponent's card: 8 Clubs
You win the hand!
Your card: Q Diamonds 	Opponent's card: 6 Spades
You win the hand!
Your card: 6 Diamonds 	Opponent's card: J Spades
You lose the hand
Your card: 10 Diamonds 	Opponent's card: Q Spades
You lose the hand
Your card: 5 Diamonds 	Opponent's card: 3 Spades
You win the hand!
Your card: 7 Diamonds 	Opponent's card: 7 Spades
WAR
Your card: 5 Clubs 	Opponent's card: A Diamonds
You win the hand!
Your card: 3 Clubs 	Opponent's card: K Clubs
You lose the hand
Your card: 5 Hearts 	Opponent's card: A Spades
You win the hand!
Your card: 6 Clubs 	Opponent's card: 3 Hearts
You win the hand!
Your card: 7 Clubs 	Opponent's card: 9 Hearts
You lose the hand
Your card: 7 Hearts 	Opponent's card: 2 Clubs
You win the hand!
Your card: 3 Diamonds 	Opponent's card: 2 Diamonds
You win the hand!
Your card: A Hearts 	Opponent's card: A Clubs
WAR
Your card: 8 Hearts 	Opponent's card: 10 Spades
You lose the hand
Your card: 10 Hearts 	Opponent's card: 8 Spades
You win the hand!
Your card: Q Hearts 	Opponent's card: Q Clubs
WAR
Your card: 9 Diamonds 	Opponent's card: 2 Spades
You win the hand!

YOU WIN: 14 x 9

Enter any key to 'q' to quitq

In [13]:
#Part 3 - Databases
import sqlite3
try:
    conn = sqlite3.connect('assignment5.db')
    conn.execute("PRAGMA foreign_keys = ON")
except Error as e:
    print(e)
    exit()
cur = conn.cursor()
cur.execute('DROP TABLE IF EXISTS courses')
cur.execute('CREATE TABLE Courses(\
                id integer PRIMARY KEY,\
                name text NOT NULL)')
cur.execute('DROP TABLE IF EXISTS student')
cur.execute('CREATE TABLE Student(\
                id integer PRIMARY KEY,\
                name text NOT NULL,\
                course1_id integer,\
                course2_id integer,\
                course3_id integer,\
                course4_id integer,\
                course5_id integer,\
                course6_id integer,\
                FOREIGN KEY (course1_id)\
                REFERENCES courses(id) ON DELETE SET NULL ON UPDATE CASCADE\
                FOREIGN KEY (course2_id)\
                REFERENCES courses(id) ON DELETE SET NULL ON UPDATE CASCADE\
                FOREIGN KEY (course3_id)\
                REFERENCES courses(id) ON DELETE SET NULL ON UPDATE CASCADE\
                FOREIGN KEY (course4_id)\
                REFERENCES courses(id) ON DELETE SET NULL ON UPDATE CASCADE\
                FOREIGN KEY (course5_id)\
                REFERENCES courses(id) ON DELETE SET NULL ON UPDATE CASCADE\
                FOREIGN KEY (course6_id)\
                REFERENCES courses(id) ON DELETE SET NULL ON UPDATE CASCADE)')
cur.execute('INSERT INTO courses (id, name) VALUES(?, ?)', (1, 'Data Programming'))
cur.execute('INSERT INTO courses (id, name) VALUES(?, ?)', (2, 'Information Encoding Standards'))
cur.execute('INSERT INTO courses (id, name) VALUES(?, ?)', (3, 'Math for Data Analytics'))
cur.execute('INSERT INTO courses (id, name) VALUES(?, ?)', (4, 'Data Systems Architecture'))
cur.execute('INSERT INTO courses (id, name) VALUES(?, ?)', (5, 'Business Process'))
cur.execute('INSERT INTO courses (id, name) VALUES(?, ?)', (6, 'Data Manipulation Techniques'))
cur.execute('INSERT INTO student (id, name, course1_id, course2_id, course3_id)\
                    VALUES (?, ?, ?, ?, ?)', (1, 'SaiBhargaviKurra', 1, 2,3 ))
cur.execute('INSERT INTO student (id, name, course1_id, course2_id)\
                    VALUES (?, ?, ?, ?)', (2, 'GopalaKrishnaSuryadevara', 3, 4))
cur.execute('INSERT INTO student (id, name, course1_id)\
                    VALUES (?, ?, ?)', (3, 'ChaithanReddyRavula', 5))
cur.execute('INSERT INTO student (id, name, course1_id, course2_id, course3_id, course4_id, course5_id, course6_id)\
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)', (4, 'Manpreet', 1, 2, 3, 4, 5, 6))
conn.commit()
cur.execute('SELECT courses.name, student.id, student.name\
                FROM student\
                INNER JOIN courses on courses.id = student.course1_id OR\
                                        courses.id = student.course2_id OR\
                                        courses.id = student.course3_id OR\
                                        courses.id = student.course4_id OR\
                                        courses.id = student.course5_id OR\
                                        courses.id = student.course6_id\
                    ORDER BY courses.name')
rows = cur.fetchall()
cur.close()
for row in rows:
    print(row)

('Business Process', 3, 'ChaithanReddyRavula')
('Business Process', 4, 'Manpreet')
('Data Manipulation Techniques', 4, 'Manpreet')
('Data Programming', 1, 'SaiBhargaviKurra')
('Data Programming', 4, 'Manpreet')
('Data Systems Architecture', 2, 'GopalaKrishnaSuryadevara')
('Data Systems Architecture', 4, 'Manpreet')
('Information Encoding Standards', 1, 'SaiBhargaviKurra')
('Information Encoding Standards', 4, 'Manpreet')
('Math for Data Analytics', 1, 'SaiBhargaviKurra')
('Math for Data Analytics', 2, 'GopalaKrishnaSuryadevara')
('Math for Data Analytics', 4, 'Manpreet')